---
abstract: 'Interface to the Affine cipher.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  Mouse: 0.93
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-Affine
provides:
  Crypt::Affine:
    file: lib/Crypt/Affine.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
